// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vq_fabric_top.h for the primary calling header

#ifndef VERILATED_VQ_FABRIC_TOP_Q_CELL_H_
#define VERILATED_VQ_FABRIC_TOP_Q_CELL_H_  // guard

#include "verilated.h"


class Vq_fabric_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vq_fabric_top_q_cell final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(i_por_n,0,0);
        VL_IN8(i_bdf_wr,0,0);
        VL_IN8(i_bdf_addr,3,0);
        VL_IN8(i_myid,3,0);
        VL_IN8(s_tick,0,0);
        VL_OUT8(o_ovf,0,0);
        VL_IN8(ri_valid,0,0);
        VL_OUT8(ri_ready,0,0);
        VL_IN8(ri_op,2,0);
        VL_IN8(ri_src,3,0);
        VL_IN8(ri_dst,3,0);
        VL_OUT8(ro_valid,0,0);
        VL_IN8(ro_ready,0,0);
        VL_OUT8(ro_op,2,0);
        VL_OUT8(ro_src,3,0);
        VL_OUT8(ro_dst,3,0);
        CData/*2:0*/ ci_op;
        CData/*0:0*/ ci_valid;
        CData/*0:0*/ ci_ready_w;
        CData/*3:0*/ ci_src;
        CData/*2:0*/ lo_op;
        CData/*0:0*/ lo_valid;
        CData/*0:0*/ lo_grant;
        CData/*3:0*/ lo_dst;
        CData/*3:0*/ lo_src;
        CData/*2:0*/ lx_op;
        CData/*0:0*/ lx_valid;
        CData/*0:0*/ lx_grant;
        CData/*3:0*/ lx_dst;
        CData/*3:0*/ lx_src;
        CData/*2:0*/ hb_cmd;
        CData/*3:0*/ hb_sel;
        CData/*3:0*/ hb_gcl;
        CData/*0:0*/ hb_done;
        CData/*0:0*/ df_wr;
        CData/*3:0*/ df_addr;
        CData/*0:0*/ df_rd;
        CData/*0:0*/ df_rstb;
        CData/*3:0*/ d_ka;
        CData/*4:0*/ d_p0e;
        CData/*0:0*/ d_mode;
        CData/*3:0*/ d_kle;
        CData/*3:0*/ d_qdw;
        CData/*3:0*/ d_qleak;
        CData/*0:0*/ d_rqen;
        CData/*3:0*/ w_indst;
        CData/*3:0*/ d_kf;
        CData/*3:0*/ d_ks;
        CData/*0:0*/ w_bound;
        CData/*3:0*/ w_cid;
        CData/*3:0*/ w_lddst;
        CData/*0:0*/ w_antic;
        CData/*0:0*/ df_wr_g;
        CData/*3:0*/ df_addr_g;
        CData/*3:0*/ done_vec;
        CData/*3:0*/ ovf_vec;
        CData/*0:0*/ ld_valid;
        CData/*0:0*/ ld_ready;
        CData/*2:0*/ ld_op;
        CData/*3:0*/ ld_src;
        CData/*0:0*/ eg_s_valid;
        CData/*0:0*/ eg_s_ready;
    };
    struct {
        CData/*2:0*/ eg_op;
        CData/*3:0*/ eg_src;
        CData/*3:0*/ eg_dst;
        CData/*0:0*/ li_valid_w;
        CData/*0:0*/ li_ready_w;
        CData/*2:0*/ li_op_w;
        CData/*3:0*/ li_src_w;
        CData/*3:0*/ li_dst_w;
        CData/*0:0*/ u_core__DOT__clk;
        CData/*0:0*/ u_core__DOT__rst_n;
        CData/*2:0*/ u_core__DOT__ci_op;
        CData/*0:0*/ u_core__DOT__ci_valid;
        CData/*0:0*/ u_core__DOT__ci_ready;
        CData/*3:0*/ u_core__DOT__ci_src;
        CData/*2:0*/ u_core__DOT__lo_op;
        CData/*0:0*/ u_core__DOT__lo_valid;
        CData/*0:0*/ u_core__DOT__lo_ready;
        CData/*3:0*/ u_core__DOT__lo_dst;
        CData/*3:0*/ u_core__DOT__lo_src;
        CData/*2:0*/ u_core__DOT__lx_op;
        CData/*0:0*/ u_core__DOT__lx_valid;
        CData/*0:0*/ u_core__DOT__lx_ready;
        CData/*3:0*/ u_core__DOT__lx_dst;
        CData/*3:0*/ u_core__DOT__lx_src;
        CData/*2:0*/ u_core__DOT__hb_cmd;
        CData/*3:0*/ u_core__DOT__hb_sel;
        CData/*3:0*/ u_core__DOT__hb_gcl;
        CData/*0:0*/ u_core__DOT__hb_done;
        CData/*0:0*/ u_core__DOT__df_wr;
        CData/*3:0*/ u_core__DOT__df_addr;
        CData/*0:0*/ u_core__DOT__df_rd;
        CData/*0:0*/ u_core__DOT__df_rstb;
        CData/*3:0*/ u_core__DOT__d_ka;
        CData/*3:0*/ u_core__DOT__d_kle;
        CData/*3:0*/ u_core__DOT__d_qdw;
        CData/*3:0*/ u_core__DOT__d_qleak;
        CData/*0:0*/ u_core__DOT__d_rqen;
        CData/*0:0*/ u_core__DOT__s_tick;
        CData/*0:0*/ u_core__DOT__bound;
        CData/*3:0*/ u_core__DOT__cell_id;
        CData/*0:0*/ u_core__DOT__o_antic;
        CData/*4:0*/ u_core__DOT__state;
        CData/*0:0*/ u_core__DOT__tick_pend;
        CData/*3:0*/ u_core__DOT__lr_src;
        CData/*3:0*/ u_core__DOT__lr_a0;
        CData/*0:0*/ u_core__DOT__resp_nak;
        CData/*2:0*/ u_core__DOT__eidx;
        CData/*0:0*/ u_core__DOT__eg_fire;
        CData/*0:0*/ u_core__DOT__eg_tick;
        CData/*0:0*/ u_core__DOT__eg_live;
        CData/*3:0*/ u_core__DOT__eg_gclass;
        CData/*0:0*/ u_core__DOT__rq_train;
        CData/*0:0*/ u_core__DOT__rq_tick;
        CData/*0:0*/ u_core__DOT__u_eg__DOT__clk;
        CData/*0:0*/ u_core__DOT__u_eg__DOT__rst_n;
        CData/*0:0*/ u_core__DOT__u_eg__DOT__i_fire;
        CData/*0:0*/ u_core__DOT__u_eg__DOT__i_tick;
        CData/*3:0*/ u_core__DOT__u_eg__DOT__i_kle;
        CData/*0:0*/ u_core__DOT__u_eg__DOT__o_live;
        CData/*3:0*/ u_core__DOT__u_eg__DOT__o_gclass;
        CData/*0:0*/ u_core__DOT__u_eg__DOT__fsnap;
        CData/*0:0*/ u_core__DOT__u_rq__DOT__clk;
        CData/*0:0*/ u_core__DOT__u_rq__DOT__rst_n;
        CData/*0:0*/ u_core__DOT__u_rq__DOT__i_train;
    };
    struct {
        CData/*0:0*/ u_core__DOT__u_rq__DOT__i_tick;
        CData/*3:0*/ u_core__DOT__u_rq__DOT__i_sel;
        CData/*3:0*/ u_core__DOT__u_rq__DOT__i_gclass;
        CData/*3:0*/ u_core__DOT__u_rq__DOT__i_qdw;
        CData/*3:0*/ u_core__DOT__u_rq__DOT__i_qleak;
        CData/*0:0*/ u_core__DOT__u_rq__DOT__i_en;
        CData/*0:0*/ u_core__DOT__u_rq__DOT__o_antic;
        CData/*1:0*/ u_core__DOT__u_rq__DOT__esel;
        CData/*3:0*/ u_core__DOT__u_rq__DOT__gcl;
        CData/*5:0*/ u_core__DOT__u_rq__DOT__dsh;
        CData/*0:0*/ u_core__DOT__u_rq__DOT__rsat;
        CData/*0:0*/ u_core__DOT__u_rq__DOT__rsnap;
        CData/*0:0*/ u_df__DOT__clk;
        CData/*0:0*/ u_df__DOT__rst_n;
        CData/*0:0*/ u_df__DOT__i_wr;
        CData/*3:0*/ u_df__DOT__i_addr;
        CData/*0:0*/ u_df__DOT__i_rd;
        CData/*0:0*/ u_df__DOT__o_rstb;
        CData/*3:0*/ u_df__DOT__o_kf;
        CData/*3:0*/ u_df__DOT__o_ks;
        CData/*3:0*/ u_df__DOT__o_ka;
        CData/*4:0*/ u_df__DOT__o_p0e;
        CData/*0:0*/ u_df__DOT__o_mode;
        CData/*3:0*/ u_df__DOT__o_kle;
        CData/*3:0*/ u_df__DOT__o_qdw;
        CData/*3:0*/ u_df__DOT__o_qleak;
        CData/*0:0*/ u_df__DOT__o_rqen;
        CData/*0:0*/ u_inbuf__DOT__clk;
        CData/*0:0*/ u_inbuf__DOT__rst_n;
        CData/*0:0*/ u_inbuf__DOT__s_valid;
        CData/*0:0*/ u_inbuf__DOT__s_ready;
        CData/*2:0*/ u_inbuf__DOT__s_op;
        CData/*3:0*/ u_inbuf__DOT__s_src;
        CData/*3:0*/ u_inbuf__DOT__s_dst;
        CData/*0:0*/ u_inbuf__DOT__m_valid;
        CData/*0:0*/ u_inbuf__DOT__m_ready;
        CData/*2:0*/ u_inbuf__DOT__m_op;
        CData/*3:0*/ u_inbuf__DOT__m_src;
        CData/*3:0*/ u_inbuf__DOT__m_dst;
        CData/*0:0*/ u_inbuf__DOT__a_v;
        CData/*0:0*/ u_inbuf__DOT__b_v;
        CData/*0:0*/ u_inbuf__DOT__push;
        CData/*0:0*/ u_inbuf__DOT__pop;
        CData/*0:0*/ u_egbuf__DOT__clk;
        CData/*0:0*/ u_egbuf__DOT__rst_n;
        CData/*0:0*/ u_egbuf__DOT__s_valid;
        CData/*0:0*/ u_egbuf__DOT__s_ready;
        CData/*2:0*/ u_egbuf__DOT__s_op;
        CData/*3:0*/ u_egbuf__DOT__s_src;
        CData/*3:0*/ u_egbuf__DOT__s_dst;
        CData/*0:0*/ u_egbuf__DOT__m_valid;
        CData/*0:0*/ u_egbuf__DOT__m_ready;
        CData/*2:0*/ u_egbuf__DOT__m_op;
        CData/*3:0*/ u_egbuf__DOT__m_src;
        CData/*3:0*/ u_egbuf__DOT__m_dst;
        CData/*0:0*/ u_egbuf__DOT__a_v;
        CData/*0:0*/ u_egbuf__DOT__b_v;
        CData/*0:0*/ u_egbuf__DOT__push;
        CData/*0:0*/ u_egbuf__DOT__pop;
        CData/*3:0*/ u_rp__DOT__i_myid;
        CData/*0:0*/ u_rp__DOT__ri_valid;
        CData/*0:0*/ u_rp__DOT__ri_ready;
        CData/*2:0*/ u_rp__DOT__ri_op;
        CData/*3:0*/ u_rp__DOT__ri_src;
    };
    struct {
        CData/*3:0*/ u_rp__DOT__ri_dst;
        CData/*0:0*/ u_rp__DOT__ro_valid;
        CData/*0:0*/ u_rp__DOT__ro_ready;
        CData/*2:0*/ u_rp__DOT__ro_op;
        CData/*3:0*/ u_rp__DOT__ro_src;
        CData/*3:0*/ u_rp__DOT__ro_dst;
        CData/*0:0*/ u_rp__DOT__li_valid;
        CData/*0:0*/ u_rp__DOT__li_ready;
        CData/*2:0*/ u_rp__DOT__li_op;
        CData/*3:0*/ u_rp__DOT__li_src;
        CData/*3:0*/ u_rp__DOT__li_dst;
        CData/*0:0*/ u_rp__DOT__ld_valid;
        CData/*0:0*/ u_rp__DOT__ld_ready;
        CData/*2:0*/ u_rp__DOT__ld_op;
        CData/*3:0*/ u_rp__DOT__ld_src;
        CData/*3:0*/ u_rp__DOT__ld_dst;
        CData/*0:0*/ u_rp__DOT__hit;
        CData/*0:0*/ u_rp__DOT__consumed;
        CData/*0:0*/ u_rp__DOT__transit;
        CData/*0:0*/ u_rp__DOT__inject_ok;
        CData/*0:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__clk;
        CData/*0:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__rst_n;
        CData/*0:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__i_sel;
        CData/*2:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__i_cmd;
        CData/*0:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__i_mode;
        CData/*4:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__i_p0e;
        CData/*3:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__i_gclass;
        CData/*0:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__o_done;
        CData/*0:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__o_ovf;
        CData/*0:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__rstate;
        CData/*4:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__ridx;
        CData/*3:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__wmsb;
        CData/*3:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__gcl;
        CData/*4:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__shl2;
        CData/*0:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__decn;
        CData/*0:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__hlend;
        CData/*0:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__g_lad_sat__DOT__sat;
        CData/*0:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__clk;
        CData/*0:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__rst_n;
        CData/*0:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__i_sel;
        CData/*2:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__i_cmd;
        CData/*0:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__i_mode;
        CData/*4:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__i_p0e;
        CData/*3:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__i_gclass;
        CData/*0:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__o_done;
        CData/*0:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__o_ovf;
        CData/*0:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__rstate;
        CData/*4:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__ridx;
        CData/*3:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__wmsb;
        CData/*3:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__gcl;
        CData/*4:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__shl2;
        CData/*0:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__decn;
        CData/*0:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__hlend;
        CData/*0:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__g_lad_sat__DOT__sat;
        CData/*0:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__clk;
        CData/*0:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__rst_n;
        CData/*0:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__i_sel;
        CData/*2:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__i_cmd;
        CData/*0:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__i_mode;
        CData/*4:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__i_p0e;
        CData/*3:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__i_gclass;
        CData/*0:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__o_done;
        CData/*0:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__o_ovf;
        CData/*0:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__rstate;
    };
    struct {
        CData/*4:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__ridx;
        CData/*3:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__wmsb;
        CData/*3:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__gcl;
        CData/*4:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__shl2;
        CData/*0:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__decn;
        CData/*0:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__hlend;
        CData/*0:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__g_lad_sat__DOT__sat;
        CData/*0:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__clk;
        CData/*0:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__rst_n;
        CData/*0:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__i_sel;
        CData/*2:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__i_cmd;
        CData/*0:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__i_mode;
        CData/*4:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__i_p0e;
        CData/*3:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__i_gclass;
        CData/*0:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__o_done;
        CData/*0:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__o_ovf;
        CData/*0:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__rstate;
        CData/*4:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__ridx;
        CData/*3:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__wmsb;
        CData/*3:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__gcl;
        CData/*4:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__shl2;
        CData/*0:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__decn;
        CData/*0:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__hlend;
        CData/*0:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__g_lad_sat__DOT__sat;
        CData/*3:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__2__Vfuncout;
        CData/*3:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__9__Vfuncout;
        CData/*3:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__16__Vfuncout;
        CData/*3:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__23__Vfuncout;
        CData/*3:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__30__Vfuncout;
        CData/*3:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__37__Vfuncout;
        CData/*3:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__44__Vfuncout;
        CData/*3:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__51__Vfuncout;
        CData/*3:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__58__Vfuncout;
        CData/*3:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__65__Vfuncout;
        CData/*3:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__72__Vfuncout;
        CData/*3:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__79__Vfuncout;
        CData/*3:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__86__Vfuncout;
        CData/*3:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__93__Vfuncout;
        CData/*3:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__100__Vfuncout;
        VL_IN16(i_bdf_wdata,15,0);
        VL_IN16(ri_a0,15,0);
        VL_IN16(ri_a1,15,0);
        VL_IN16(ri_a2,15,0);
        VL_IN16(ri_dat,15,0);
        VL_OUT16(ro_a0,15,0);
        VL_OUT16(ro_a1,15,0);
        VL_OUT16(ro_a2,15,0);
        VL_OUT16(ro_dat,15,0);
        SData/*15:0*/ ci_a0;
        SData/*15:0*/ ci_a1;
        SData/*15:0*/ ci_a2;
        SData/*15:0*/ ci_dat;
        SData/*15:0*/ lo_a0;
        SData/*15:0*/ lo_a1;
        SData/*15:0*/ lo_a2;
        SData/*15:0*/ lo_dat;
        SData/*15:0*/ lx_a0;
        SData/*15:0*/ lx_a1;
        SData/*15:0*/ lx_a2;
        SData/*15:0*/ lx_dat;
        SData/*15:0*/ hb_base;
        SData/*15:0*/ hb_w;
        SData/*15:0*/ w_ftrace;
        SData/*15:0*/ df_wdata;
    };
    struct {
        SData/*15:0*/ df_rdata;
        SData/*15:0*/ d_thresh;
        SData/*15:0*/ d_refr;
        SData/*15:0*/ d_hl;
        SData/*15:0*/ d_floor;
        SData/*15:0*/ d_eta_f;
        SData/*15:0*/ d_eta_s;
        SData/*15:0*/ d_cosmin;
        SData/*15:0*/ w_act;
        SData/*15:0*/ df_wdata_g;
        SData/*15:0*/ hb_w_mux;
        SData/*15:0*/ ld_a0;
        SData/*15:0*/ ld_a1;
        SData/*15:0*/ ld_a2;
        SData/*15:0*/ ld_dat;
        SData/*15:0*/ eg_a0;
        SData/*15:0*/ eg_a1;
        SData/*15:0*/ eg_a2;
        SData/*15:0*/ eg_dat;
        SData/*15:0*/ li_a0_w;
        SData/*15:0*/ li_a1_w;
        SData/*15:0*/ li_a2_w;
        SData/*15:0*/ li_dat_w;
        SData/*15:0*/ u_core__DOT__ci_a0;
        SData/*15:0*/ u_core__DOT__ci_a1;
        SData/*15:0*/ u_core__DOT__ci_a2;
        SData/*15:0*/ u_core__DOT__ci_dat;
        SData/*15:0*/ u_core__DOT__lo_a0;
        SData/*15:0*/ u_core__DOT__lo_a1;
        SData/*15:0*/ u_core__DOT__lo_a2;
        SData/*15:0*/ u_core__DOT__lo_dat;
        SData/*15:0*/ u_core__DOT__lx_a0;
        SData/*15:0*/ u_core__DOT__lx_a1;
        SData/*15:0*/ u_core__DOT__lx_a2;
        SData/*15:0*/ u_core__DOT__lx_dat;
        SData/*15:0*/ u_core__DOT__hb_base;
        SData/*15:0*/ u_core__DOT__hb_w;
        SData/*15:0*/ u_core__DOT__df_wdata;
        SData/*15:0*/ u_core__DOT__df_rdata;
        SData/*15:0*/ u_core__DOT__d_thresh;
        SData/*15:0*/ u_core__DOT__d_refr;
        SData/*15:0*/ u_core__DOT__d_floor;
        SData/*15:0*/ u_core__DOT__act;
        SData/*15:0*/ u_core__DOT__o_ftrace;
        SData/*15:0*/ u_core__DOT__lr_a1;
        SData/*15:0*/ u_core__DOT__lr_a2;
        SData/*15:0*/ u_core__DOT__lr_dat;
        SData/*15:0*/ u_core__DOT__viewdat;
        SData/*15:0*/ u_core__DOT__refr;
        SData/*15:0*/ u_core__DOT__afire;
        SData/*15:0*/ u_core__DOT__eff_w;
        SData/*15:0*/ u_core__DOT__rq_credit;
        SData/*15:0*/ u_core__DOT__hb_wq;
        SData/*11:0*/ u_core__DOT__ci_a0_rsvd;
        SData/*15:0*/ u_core__DOT__u_eg__DOT__i_floor;
        SData/*15:0*/ u_core__DOT__u_eg__DOT__o_f;
        SData/*15:0*/ u_core__DOT__u_eg__DOT__f;
        SData/*15:0*/ u_core__DOT__u_eg__DOT__fleak;
        SData/*15:0*/ u_core__DOT__u_rq__DOT__o_credit;
        SData/*15:0*/ u_core__DOT__u_rq__DOT__rsel;
        SData/*15:0*/ u_core__DOT__u_rq__DOT__rdepn;
        SData/*15:0*/ u_core__DOT__u_rq__DOT__rleak;
        SData/*15:0*/ u_core__DOT__u_rq__DOT__rleakn;
        SData/*15:0*/ u_df__DOT__i_wdata;
    };
    struct {
        SData/*15:0*/ u_df__DOT__o_rdata;
        SData/*15:0*/ u_df__DOT__o_eta_f;
        SData/*15:0*/ u_df__DOT__o_eta_s;
        SData/*15:0*/ u_df__DOT__o_thresh;
        SData/*15:0*/ u_df__DOT__o_refr;
        SData/*15:0*/ u_df__DOT__o_cosmin;
        SData/*15:0*/ u_df__DOT__o_hl;
        SData/*15:0*/ u_df__DOT__i_probe;
        SData/*15:0*/ u_df__DOT__o_floor;
        SData/*15:0*/ u_inbuf__DOT__s_a0;
        SData/*15:0*/ u_inbuf__DOT__s_a1;
        SData/*15:0*/ u_inbuf__DOT__s_a2;
        SData/*15:0*/ u_inbuf__DOT__s_dat;
        SData/*15:0*/ u_inbuf__DOT__m_a0;
        SData/*15:0*/ u_inbuf__DOT__m_a1;
        SData/*15:0*/ u_inbuf__DOT__m_a2;
        SData/*15:0*/ u_inbuf__DOT__m_dat;
        SData/*15:0*/ u_egbuf__DOT__s_a0;
        SData/*15:0*/ u_egbuf__DOT__s_a1;
        SData/*15:0*/ u_egbuf__DOT__s_a2;
        SData/*15:0*/ u_egbuf__DOT__s_dat;
        SData/*15:0*/ u_egbuf__DOT__m_a0;
        SData/*15:0*/ u_egbuf__DOT__m_a1;
        SData/*15:0*/ u_egbuf__DOT__m_a2;
        SData/*15:0*/ u_egbuf__DOT__m_dat;
        SData/*15:0*/ u_rp__DOT__ri_a0;
        SData/*15:0*/ u_rp__DOT__ri_a1;
        SData/*15:0*/ u_rp__DOT__ri_a2;
        SData/*15:0*/ u_rp__DOT__ri_dat;
        SData/*15:0*/ u_rp__DOT__ro_a0;
        SData/*15:0*/ u_rp__DOT__ro_a1;
        SData/*15:0*/ u_rp__DOT__ro_a2;
        SData/*15:0*/ u_rp__DOT__ro_dat;
        SData/*15:0*/ u_rp__DOT__li_a0;
        SData/*15:0*/ u_rp__DOT__li_a1;
        SData/*15:0*/ u_rp__DOT__li_a2;
        SData/*15:0*/ u_rp__DOT__li_dat;
        SData/*15:0*/ u_rp__DOT__ld_a0;
        SData/*15:0*/ u_rp__DOT__ld_a1;
        SData/*15:0*/ u_rp__DOT__ld_a2;
        SData/*15:0*/ u_rp__DOT__ld_dat;
        SData/*15:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__i_base;
        SData/*15:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__i_hl;
        SData/*15:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__o_w;
        SData/*15:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__hl_cnt;
        SData/*15:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__wh;
        SData/*15:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__base;
        SData/*15:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__lad;
        SData/*15:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__whs;
        SData/*15:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__eng;
        SData/*15:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__wout;
        SData/*15:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__i_base;
        SData/*15:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__i_hl;
        SData/*15:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__o_w;
        SData/*15:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__hl_cnt;
        SData/*15:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__wh;
        SData/*15:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__base;
        SData/*15:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__lad;
        SData/*15:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__whs;
        SData/*15:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__eng;
        SData/*15:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__wout;
        SData/*15:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__i_base;
        SData/*15:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__i_hl;
        SData/*15:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__o_w;
    };
    struct {
        SData/*15:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__hl_cnt;
        SData/*15:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__wh;
        SData/*15:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__base;
        SData/*15:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__lad;
        SData/*15:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__whs;
        SData/*15:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__eng;
        SData/*15:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__wout;
        SData/*15:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__i_base;
        SData/*15:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__i_hl;
        SData/*15:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__o_w;
        SData/*15:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__hl_cnt;
        SData/*15:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__wh;
        SData/*15:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__base;
        SData/*15:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__lad;
        SData/*15:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__whs;
        SData/*15:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__eng;
        SData/*15:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__wout;
        SData/*15:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__2__v;
        SData/*15:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__9__v;
        SData/*15:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__16__v;
        SData/*15:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__23__v;
        SData/*15:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__30__v;
        SData/*15:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__37__v;
        SData/*15:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__44__v;
        SData/*15:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__51__v;
        SData/*15:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__58__v;
        SData/*15:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__65__v;
        SData/*15:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__72__v;
        SData/*15:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__79__v;
        SData/*15:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__86__v;
        SData/*15:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__93__v;
        SData/*15:0*/ __Vfunc_u_core__DOT__u_eg__DOT__msb_idx__100__v;
        IData/*31:0*/ i;
        IData/*18:0*/ u_core__DOT__wacc;
        IData/*16:0*/ u_core__DOT__w_rq;
        IData/*31:0*/ u_core__DOT__i;
        IData/*31:0*/ u_core__DOT__u_eg__DOT__msb_idx__Vstatic__j;
        IData/*31:0*/ u_core__DOT__u_rq__DOT__i;
        IData/*31:0*/ u_core__DOT__u_rq__DOT__j;
        IData/*31:0*/ u_core__DOT__u_rq__DOT__qbase;
        IData/*31:0*/ u_core__DOT__u_rq__DOT__dep;
        IData/*31:0*/ u_core__DOT__u_rq__DOT__cred_cur;
        IData/*31:0*/ u_core__DOT__u_rq__DOT__cred_new;
        VlWide<3>/*74:0*/ u_inbuf__DOT__a_q;
        VlWide<3>/*74:0*/ u_inbuf__DOT__b_q;
        VlWide<3>/*74:0*/ u_inbuf__DOT__s_bus;
        VlWide<3>/*74:0*/ u_egbuf__DOT__a_q;
        VlWide<3>/*74:0*/ u_egbuf__DOT__b_q;
        VlWide<3>/*74:0*/ u_egbuf__DOT__s_bus;
        IData/*31:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__msb16__Vstatic__j;
        IData/*23:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__age;
        IData/*16:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__acc;
        IData/*31:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__j;
        IData/*31:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__p0;
        IData/*31:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__ivr;
        IData/*31:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__ival;
        IData/*31:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__agen;
        IData/*16:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__hlc;
        IData/*16:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__hlth;
        IData/*31:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__ridx32;
        IData/*31:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__rsh;
        IData/*16:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__addw;
        IData/*16:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__wfin;
        IData/*31:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__msb16__Vstatic__j;
    };
    struct {
        IData/*23:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__age;
        IData/*16:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__acc;
        IData/*31:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__j;
        IData/*31:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__p0;
        IData/*31:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__ivr;
        IData/*31:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__ival;
        IData/*31:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__agen;
        IData/*16:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__hlc;
        IData/*16:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__hlth;
        IData/*31:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__ridx32;
        IData/*31:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__rsh;
        IData/*16:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__addw;
        IData/*16:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__wfin;
        IData/*31:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__msb16__Vstatic__j;
        IData/*23:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__age;
        IData/*16:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__acc;
        IData/*31:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__j;
        IData/*31:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__p0;
        IData/*31:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__ivr;
        IData/*31:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__ival;
        IData/*31:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__agen;
        IData/*16:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__hlc;
        IData/*16:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__hlth;
        IData/*31:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__ridx32;
        IData/*31:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__rsh;
        IData/*16:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__addw;
        IData/*16:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__wfin;
        IData/*31:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__msb16__Vstatic__j;
        IData/*23:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__age;
        IData/*16:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__acc;
        IData/*31:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__j;
        IData/*31:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__p0;
        IData/*31:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__ivr;
        IData/*31:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__ival;
        IData/*31:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__agen;
        IData/*16:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__hlc;
        IData/*16:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__hlth;
        IData/*31:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__ridx32;
        IData/*31:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__rsh;
        IData/*16:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__addw;
        IData/*16:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__wfin;
        QData/*63:0*/ w_flat;
        QData/*32:0*/ u_core__DOT__eff_p;
        QData/*35:0*/ u_core__DOT__act_e;
        QData/*32:0*/ u_core__DOT__prod;
        QData/*35:0*/ u_core__DOT__prod_e;
        QData/*35:0*/ u_core__DOT__eff_sum;
        QData/*32:0*/ u_core__DOT__prod_p;
        QData/*35:0*/ u_core__DOT__eff_pe;
        QData/*35:0*/ u_core__DOT__leak_sum;
        QData/*32:0*/ u_core__DOT__u_rq__DOT__rsum;
        QData/*32:0*/ u_core__DOT__u_rq__DOT__rfull;
        VlUnpacked<CData/*3:0*/, 4> u_core__DOT__etab;
        VlUnpacked<CData/*0:0*/, 4> u_core__DOT__ev;
        VlUnpacked<SData/*15:0*/, 4> u_core__DOT__u_rq__DOT__R;
        VlUnpacked<SData/*15:0*/, 16> u_df__DOT__dial;
        VlUnpacked<CData/*7:0*/, 8> edges__BRA__0__KET____DOT__u_hebb__DOT__c;
        VlUnpacked<CData/*7:0*/, 8> edges__BRA__1__KET____DOT__u_hebb__DOT__c;
        VlUnpacked<CData/*7:0*/, 8> edges__BRA__2__KET____DOT__u_hebb__DOT__c;
        VlUnpacked<CData/*7:0*/, 8> edges__BRA__3__KET____DOT__u_hebb__DOT__c;
    };

    // INTERNAL VARIABLES
    Vq_fabric_top__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*2:0*/ u_core__DOT__OP_BIND = 0U;
    static constexpr CData/*2:0*/ u_core__DOT__OP_LINK = 1U;
    static constexpr CData/*2:0*/ u_core__DOT__OP_EFF = 2U;
    static constexpr CData/*2:0*/ u_core__DOT__OP_VIEW = 3U;
    static constexpr CData/*2:0*/ u_core__DOT__OP_TICK = 4U;
    static constexpr CData/*2:0*/ u_core__DOT__OP_ACK = 5U;
    static constexpr CData/*2:0*/ u_core__DOT__OP_NAK = 6U;
    static constexpr CData/*4:0*/ u_core__DOT__ST_RST = 0U;
    static constexpr CData/*4:0*/ u_core__DOT__ST_UNB = 1U;
    static constexpr CData/*4:0*/ u_core__DOT__ST_IDLE = 2U;
    static constexpr CData/*4:0*/ u_core__DOT__ST_BIND = 3U;
    static constexpr CData/*4:0*/ u_core__DOT__ST_LINK = 4U;
    static constexpr CData/*4:0*/ u_core__DOT__ST_LNKW = 5U;
    static constexpr CData/*4:0*/ u_core__DOT__ST_EFF = 6U;
    static constexpr CData/*4:0*/ u_core__DOT__ST_EFFT = 7U;
    static constexpr CData/*4:0*/ u_core__DOT__ST_EFFR = 8U;
    static constexpr CData/*4:0*/ u_core__DOT__ST_VIEW = 9U;
    static constexpr CData/*4:0*/ u_core__DOT__ST_VACC = 0x0aU;
    static constexpr CData/*4:0*/ u_core__DOT__ST_VACW = 0x0bU;
    static constexpr CData/*4:0*/ u_core__DOT__ST_VRD = 0x0cU;
    static constexpr CData/*4:0*/ u_core__DOT__ST_RESP = 0x0dU;
    static constexpr CData/*4:0*/ u_core__DOT__ST_TICK = 0x0eU;
    static constexpr CData/*4:0*/ u_core__DOT__ST_TSW = 0x0fU;
    static constexpr CData/*4:0*/ u_core__DOT__ST_TSWW = 0x10U;
    static constexpr CData/*4:0*/ u_core__DOT__ST_TLEAK = 0x11U;
    static constexpr CData/*4:0*/ u_core__DOT__ST_FIRE = 0x12U;
    static constexpr CData/*4:0*/ u_core__DOT__ST_EFFI = 0x13U;
    static constexpr CData/*4:0*/ u_core__DOT__ST_EFFP = 0x14U;
    static constexpr CData/*4:0*/ u_core__DOT__ST_EFFM = 0x15U;
    static constexpr CData/*3:0*/ u_core__DOT__u_eg__DOT__TOPJ = 0x0fU;
    static constexpr CData/*3:0*/ u_core__DOT__u_rq__DOT__K4 = 8U;
    static constexpr CData/*3:0*/ u_df__DOT__D_ETA_F = 0U;
    static constexpr CData/*3:0*/ u_df__DOT__D_ETA_S = 1U;
    static constexpr CData/*3:0*/ u_df__DOT__D_KF = 2U;
    static constexpr CData/*3:0*/ u_df__DOT__D_KS = 3U;
    static constexpr CData/*3:0*/ u_df__DOT__D_KA = 4U;
    static constexpr CData/*3:0*/ u_df__DOT__D_THRESH = 5U;
    static constexpr CData/*3:0*/ u_df__DOT__D_REFR = 6U;
    static constexpr CData/*3:0*/ u_df__DOT__D_COSMIN = 7U;
    static constexpr CData/*3:0*/ u_df__DOT__D_P0E = 8U;
    static constexpr CData/*3:0*/ u_df__DOT__D_MODE = 9U;
    static constexpr CData/*3:0*/ u_df__DOT__D_HL = 0x0aU;
    static constexpr CData/*3:0*/ u_df__DOT__D_KLE = 0x0bU;
    static constexpr CData/*3:0*/ u_df__DOT__D_FLOOR = 0x0cU;
    static constexpr CData/*3:0*/ u_df__DOT__D_FTRACE = 0x0dU;
    static constexpr CData/*3:0*/ u_df__DOT__D_RQ = 0x0eU;
    static constexpr CData/*3:0*/ u_df__DOT__D_RQL = 0x0fU;
    static constexpr CData/*3:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__K4 = 8U;
    static constexpr CData/*3:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__K4 = 8U;
    static constexpr CData/*3:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__K4 = 8U;
    static constexpr CData/*3:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__K4 = 8U;
    static constexpr IData/*31:0*/ OPW = 3U;
    static constexpr IData/*31:0*/ AIDW = 4U;
    static constexpr IData/*31:0*/ PW = 0x00000010U;
    static constexpr IData/*31:0*/ EDGES_N = 4U;
    static constexpr IData/*31:0*/ EIW = 2U;
    static constexpr IData/*31:0*/ K = 8U;
    static constexpr IData/*31:0*/ B = 8U;
    static constexpr IData/*31:0*/ AGEW = 0x00000018U;
    static constexpr IData/*31:0*/ u_core__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ u_core__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ u_core__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ u_core__DOT__EDGES_N = 4U;
    static constexpr IData/*31:0*/ u_core__DOT__EIW = 2U;
    static constexpr IData/*31:0*/ u_core__DOT__K = 8U;
    static constexpr IData/*31:0*/ u_core__DOT__PIPE_EFF = 1U;
    static constexpr IData/*31:0*/ u_core__DOT__u_eg__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ u_core__DOT__u_rq__DOT__RW = 0x00000010U;
    static constexpr IData/*31:0*/ u_core__DOT__u_rq__DOT__K = 8U;
    static constexpr IData/*31:0*/ u_core__DOT__u_rq__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ u_core__DOT__u_rq__DOT__EDGES_N = 4U;
    static constexpr IData/*31:0*/ u_core__DOT__u_rq__DOT__EIW = 2U;
    static constexpr IData/*31:0*/ u_df__DOT__DW = 0x00000010U;
    static constexpr IData/*31:0*/ u_df__DOT__ND = 0x00000010U;
    static constexpr IData/*31:0*/ u_df__DOT__AW = 4U;
    static constexpr IData/*31:0*/ u_inbuf__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ u_inbuf__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ u_inbuf__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ u_inbuf__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ u_egbuf__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ u_egbuf__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ u_egbuf__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ u_egbuf__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ u_rp__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ u_rp__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ u_rp__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__K = 8U;
    static constexpr IData/*31:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__B = 8U;
    static constexpr IData/*31:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__AGEW = 0x00000018U;
    static constexpr IData/*31:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__AW = 0x00000011U;
    static constexpr IData/*31:0*/ edges__BRA__0__KET____DOT__u_hebb__DOT__IIW = 3U;
    static constexpr IData/*31:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__K = 8U;
    static constexpr IData/*31:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__B = 8U;
    static constexpr IData/*31:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__AGEW = 0x00000018U;
    static constexpr IData/*31:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__AW = 0x00000011U;
    static constexpr IData/*31:0*/ edges__BRA__1__KET____DOT__u_hebb__DOT__IIW = 3U;
    static constexpr IData/*31:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__K = 8U;
    static constexpr IData/*31:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__B = 8U;
    static constexpr IData/*31:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__AGEW = 0x00000018U;
    static constexpr IData/*31:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__AW = 0x00000011U;
    static constexpr IData/*31:0*/ edges__BRA__2__KET____DOT__u_hebb__DOT__IIW = 3U;
    static constexpr IData/*31:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__K = 8U;
    static constexpr IData/*31:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__B = 8U;
    static constexpr IData/*31:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__AGEW = 0x00000018U;
    static constexpr IData/*31:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__AW = 0x00000011U;
    static constexpr IData/*31:0*/ edges__BRA__3__KET____DOT__u_hebb__DOT__IIW = 3U;

    // CONSTRUCTORS
    Vq_fabric_top_q_cell(Vq_fabric_top__Syms* symsp, const char* v__name);
    ~Vq_fabric_top_q_cell();
    VL_UNCOPYABLE(Vq_fabric_top_q_cell);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
