// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vq_fabric_top.h for the primary calling header

#ifndef VERILATED_VQ_FABRIC_TOP___024ROOT_H_
#define VERILATED_VQ_FABRIC_TOP___024ROOT_H_  // guard

#include "verilated.h"
class Vq_fabric_top_q_cell;


class Vq_fabric_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vq_fabric_top___024root final : public VerilatedModule {
  public:
    // CELLS
    Vq_fabric_top_q_cell* __PVT__q_fabric_top__DOT__nodes__BRA__0__KET____DOT__conn0__DOT__u_cell;
    Vq_fabric_top_q_cell* __PVT__q_fabric_top__DOT__nodes__BRA__1__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell* __PVT__q_fabric_top__DOT__nodes__BRA__2__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell* __PVT__q_fabric_top__DOT__nodes__BRA__3__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell* __PVT__q_fabric_top__DOT__nodes__BRA__4__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell* __PVT__q_fabric_top__DOT__nodes__BRA__5__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell* __PVT__q_fabric_top__DOT__nodes__BRA__6__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell* __PVT__q_fabric_top__DOT__nodes__BRA__7__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell* __PVT__q_fabric_top__DOT__nodes__BRA__8__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell* __PVT__q_fabric_top__DOT__nodes__BRA__9__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell* __PVT__q_fabric_top__DOT__nodes__BRA__10__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell* __PVT__q_fabric_top__DOT__nodes__BRA__11__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell* __PVT__q_fabric_top__DOT__nodes__BRA__12__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell* __PVT__q_fabric_top__DOT__nodes__BRA__13__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell* __PVT__q_fabric_top__DOT__nodes__BRA__14__KET____DOT__connc__DOT__u_cell;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(i_val,0,0);
        VL_OUT8(o_rdy,0,0);
        VL_IN8(i_op,2,0);
        VL_IN8(i_src,3,0);
        VL_IN8(i_dst,3,0);
        VL_OUT8(o_val,0,0);
        VL_IN8(i_rdy,0,0);
        VL_OUT8(o_op,2,0);
        VL_OUT8(o_src,3,0);
        VL_OUT8(o_dst,3,0);
        VL_OUT8(o_ovf,0,0);
        CData/*0:0*/ q_fabric_top__DOT__clk;
        CData/*0:0*/ q_fabric_top__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__i_val;
        CData/*0:0*/ q_fabric_top__DOT__o_rdy;
        CData/*2:0*/ q_fabric_top__DOT__i_op;
        CData/*3:0*/ q_fabric_top__DOT__i_src;
        CData/*3:0*/ q_fabric_top__DOT__i_dst;
        CData/*0:0*/ q_fabric_top__DOT__o_val;
        CData/*0:0*/ q_fabric_top__DOT__i_rdy;
        CData/*2:0*/ q_fabric_top__DOT__o_op;
        CData/*3:0*/ q_fabric_top__DOT__o_src;
        CData/*3:0*/ q_fabric_top__DOT__o_dst;
        CData/*0:0*/ q_fabric_top__DOT__o_ovf;
        CData/*0:0*/ q_fabric_top__DOT__tick;
        CData/*0:0*/ q_fabric_top__DOT__u_ts__DOT__clk;
        CData/*0:0*/ q_fabric_top__DOT__u_ts__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__u_ts__DOT__o_tick;
        CData/*7:0*/ q_fabric_top__DOT__u_ts__DOT__cnt;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__clk;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__s_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__s_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__s_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__s_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__s_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__m_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__m_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__m_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__m_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__m_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__a_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__b_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__push;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__pop;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__clk;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__s_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__s_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__s_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__s_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__s_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__m_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__m_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__m_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__m_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__m_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__a_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__b_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__push;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__pop;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__clk;
    };
    struct {
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__s_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__s_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__s_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__s_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__s_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__m_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__m_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__m_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__m_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__m_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__a_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__b_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__push;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__pop;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__clk;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__s_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__s_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__s_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__s_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__s_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__m_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__m_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__m_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__m_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__m_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__a_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__b_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__push;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__pop;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__clk;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__s_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__s_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__s_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__s_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__s_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__m_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__m_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__m_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__m_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__m_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__a_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__b_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__push;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__pop;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__clk;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__s_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__s_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__s_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__s_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__s_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__m_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__m_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__m_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__m_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__m_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__a_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__b_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__push;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__pop;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__clk;
    };
    struct {
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__s_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__s_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__s_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__s_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__s_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__m_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__m_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__m_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__m_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__m_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__a_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__b_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__push;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__pop;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__clk;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__s_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__s_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__s_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__s_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__s_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__m_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__m_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__m_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__m_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__m_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__a_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__b_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__push;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__pop;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__clk;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__s_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__s_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__s_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__s_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__s_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__m_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__m_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__m_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__m_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__m_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__a_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__b_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__push;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__pop;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__clk;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__s_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__s_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__s_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__s_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__s_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__m_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__m_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__m_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__m_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__m_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__a_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__b_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__push;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__pop;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__clk;
    };
    struct {
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__s_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__s_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__s_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__s_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__s_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__m_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__m_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__m_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__m_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__m_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__a_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__b_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__push;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__pop;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__clk;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__s_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__s_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__s_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__s_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__s_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__m_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__m_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__m_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__m_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__m_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__a_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__b_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__push;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__pop;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__clk;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__s_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__s_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__s_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__s_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__s_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__m_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__m_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__m_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__m_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__m_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__a_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__b_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__push;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__pop;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__clk;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__s_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__s_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__s_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__s_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__s_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__m_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__m_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__m_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__m_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__m_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__a_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__b_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__push;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__pop;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__clk;
    };
    struct {
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__s_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__s_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__s_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__s_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__s_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__m_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__m_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__m_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__m_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__m_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__a_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__b_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__push;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__pop;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ri_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ri_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ri_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ri_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ri_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ro_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ro_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ro_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ro_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ro_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__i_val;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__o_rdy;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__i_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__i_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__i_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__o_val;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__i_rdy;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__o_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__o_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__o_dst;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__i_myid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ri_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ri_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ri_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ri_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ri_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ro_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ro_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ro_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ro_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ro_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__li_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__li_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__li_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__li_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__li_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ld_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ld_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ld_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ld_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ld_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__hit;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__consumed;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__transit;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__inject_ok;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__clk;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__rst_n;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__s_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__s_ready;
    };
    struct {
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__s_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__s_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__s_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__m_valid;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__m_ready;
        CData/*2:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__m_op;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__m_src;
        CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__m_dst;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__a_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__b_v;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__push;
        CData/*0:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__pop;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__q_fabric_top__DOT__nodes__BRA__0__KET____DOT__conn0__DOT__u_cell__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__q_fabric_top__DOT__nodes__BRA__1__KET____DOT__connc__DOT__u_cell__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__q_fabric_top__DOT__nodes__BRA__2__KET____DOT__connc__DOT__u_cell__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__q_fabric_top__DOT__nodes__BRA__3__KET____DOT__connc__DOT__u_cell__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__q_fabric_top__DOT__nodes__BRA__4__KET____DOT__connc__DOT__u_cell__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__q_fabric_top__DOT__nodes__BRA__5__KET____DOT__connc__DOT__u_cell__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__q_fabric_top__DOT__nodes__BRA__6__KET____DOT__connc__DOT__u_cell__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__q_fabric_top__DOT__nodes__BRA__7__KET____DOT__connc__DOT__u_cell__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__q_fabric_top__DOT__nodes__BRA__8__KET____DOT__connc__DOT__u_cell__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__q_fabric_top__DOT__nodes__BRA__9__KET____DOT__connc__DOT__u_cell__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__q_fabric_top__DOT__nodes__BRA__10__KET____DOT__connc__DOT__u_cell__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__q_fabric_top__DOT__nodes__BRA__11__KET____DOT__connc__DOT__u_cell__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__q_fabric_top__DOT__nodes__BRA__12__KET____DOT__connc__DOT__u_cell__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__q_fabric_top__DOT__nodes__BRA__13__KET____DOT__connc__DOT__u_cell__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__q_fabric_top__DOT__nodes__BRA__14__KET____DOT__connc__DOT__u_cell__clk__0;
        CData/*0:0*/ __VactContinue;
        VL_IN16(i_a0,15,0);
        VL_IN16(i_a1,15,0);
        VL_IN16(i_a2,15,0);
        VL_IN16(i_dat,15,0);
        VL_OUT16(o_a0,15,0);
        VL_OUT16(o_a1,15,0);
        VL_OUT16(o_a2,15,0);
        VL_OUT16(o_dat,15,0);
        SData/*15:0*/ q_fabric_top__DOT__i_a0;
        SData/*15:0*/ q_fabric_top__DOT__i_a1;
        SData/*15:0*/ q_fabric_top__DOT__i_a2;
        SData/*15:0*/ q_fabric_top__DOT__i_dat;
        SData/*15:0*/ q_fabric_top__DOT__o_a0;
        SData/*15:0*/ q_fabric_top__DOT__o_a1;
        SData/*15:0*/ q_fabric_top__DOT__o_a2;
        SData/*15:0*/ q_fabric_top__DOT__o_dat;
        SData/*15:0*/ q_fabric_top__DOT__nv;
        SData/*15:0*/ q_fabric_top__DOT__nr;
        SData/*15:0*/ q_fabric_top__DOT__pv;
        SData/*15:0*/ q_fabric_top__DOT__pr;
        SData/*14:0*/ q_fabric_top__DOT__ovf_cells;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__s_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__s_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__s_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__s_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__m_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__m_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__m_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__m_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__s_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__s_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__s_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__s_dat;
    };
    struct {
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__m_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__m_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__m_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__m_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__s_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__s_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__s_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__s_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__m_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__m_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__m_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__m_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__s_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__s_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__s_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__s_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__m_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__m_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__m_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__m_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__s_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__s_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__s_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__s_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__m_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__m_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__m_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__m_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__s_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__s_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__s_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__s_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__m_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__m_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__m_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__m_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__s_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__s_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__s_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__s_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__m_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__m_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__m_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__m_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__s_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__s_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__s_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__s_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__m_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__m_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__m_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__m_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__s_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__s_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__s_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__s_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__m_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__m_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__m_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__m_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__s_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__s_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__s_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__s_dat;
    };
    struct {
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__m_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__m_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__m_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__m_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__s_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__s_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__s_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__s_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__m_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__m_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__m_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__m_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__s_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__s_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__s_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__s_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__m_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__m_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__m_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__m_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__s_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__s_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__s_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__s_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__m_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__m_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__m_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__m_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__s_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__s_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__s_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__s_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__m_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__m_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__m_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__m_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__s_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__s_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__s_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__s_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__m_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__m_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__m_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__m_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ri_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ri_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ri_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ri_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ro_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ro_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ro_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__ro_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__i_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__i_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__i_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__i_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__o_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__o_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__o_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__o_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ri_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ri_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ri_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ri_dat;
    };
    struct {
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ro_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ro_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ro_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ro_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__li_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__li_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__li_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__li_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ld_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ld_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ld_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__ld_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__s_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__s_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__s_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__s_dat;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__m_a0;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__m_a1;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__m_a2;
        SData/*15:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__m_dat;
        VlWide<8>/*255:0*/ q_fabric_top__DOT__na0;
        VlWide<8>/*255:0*/ q_fabric_top__DOT__na1;
        VlWide<8>/*255:0*/ q_fabric_top__DOT__na2;
        VlWide<8>/*255:0*/ q_fabric_top__DOT__ndat;
        VlWide<8>/*255:0*/ q_fabric_top__DOT__pa0;
        VlWide<8>/*255:0*/ q_fabric_top__DOT__pa1;
        VlWide<8>/*255:0*/ q_fabric_top__DOT__pa2;
        VlWide<8>/*255:0*/ q_fabric_top__DOT__pdat;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__a_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__b_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__s_bus;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__a_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__b_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__s_bus;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__a_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__b_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__s_bus;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__a_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__b_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__s_bus;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__a_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__b_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__s_bus;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__a_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__b_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__s_bus;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__a_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__b_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__s_bus;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__a_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__b_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__s_bus;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__a_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__b_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__s_bus;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__a_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__b_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__s_bus;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__a_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__b_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__s_bus;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__a_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__b_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__s_bus;
    };
    struct {
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__a_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__b_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__s_bus;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__a_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__b_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__s_bus;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__a_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__b_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__s_bus;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__a_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__b_q;
        VlWide<3>/*74:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__s_bus;
        IData/*31:0*/ __VactIterCount;
        QData/*47:0*/ q_fabric_top__DOT__nop;
        QData/*63:0*/ q_fabric_top__DOT__nsrc;
        QData/*63:0*/ q_fabric_top__DOT__ndst;
        QData/*47:0*/ q_fabric_top__DOT__pop;
        QData/*63:0*/ q_fabric_top__DOT__psrc;
        QData/*63:0*/ q_fabric_top__DOT__pdst;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<16> __VactTriggered;
    VlTriggerVec<16> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vq_fabric_top__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*3:0*/ q_fabric_top__DOT__EXTID = 0x0fU;
    static constexpr CData/*3:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__EXTID = 0x0fU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__NCELL = 0x0000000fU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__EDGES_N = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__TPW = 8U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__NB = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__u_ts__DOT__TPW = 8U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__0__KET____DOT__u_pipe__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__1__KET____DOT__u_pipe__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__2__KET____DOT__u_pipe__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__3__KET____DOT__u_pipe__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__4__KET____DOT__u_pipe__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__5__KET____DOT__u_pipe__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__6__KET____DOT__u_pipe__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__7__KET____DOT__u_pipe__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__8__KET____DOT__u_pipe__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__9__KET____DOT__u_pipe__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__10__KET____DOT__u_pipe__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__11__KET____DOT__u_pipe__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__12__KET____DOT__u_pipe__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__13__KET____DOT__u_pipe__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__14__KET____DOT__u_pipe__DOT__FW = 0x0000004bU;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__connio__DOT__u_io__DOT__u_rp__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__OPW = 3U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__AIDW = 4U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__PW = 0x00000010U;
    static constexpr IData/*31:0*/ q_fabric_top__DOT__nodes__BRA__15__KET____DOT__u_pipe__DOT__FW = 0x0000004bU;

    // CONSTRUCTORS
    Vq_fabric_top___024root(Vq_fabric_top__Syms* symsp, const char* v__name);
    ~Vq_fabric_top___024root();
    VL_UNCOPYABLE(Vq_fabric_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
