#!/usr/bin/env python3
"""verify.py -- the Law 5 gate for the tower pilot (tools/tower).

Compiles the generated C middle layer with a host-side stub (gcc / cc /
clang, whichever exists; if none, falls back to a syntax check) and
asserts, against an INDEPENDENT Python model of the cell plus a
hand-computed golden table, that:

  1. the rendering chain (raw mV -> median -> equation -> whole psi)
     reproduces the golden (voltage -> PSI) table to whole-unit exactness,
     both on-lattice points (every 400 mV is exactly 15 psi) and
     off-lattice points, including both clamp edges;
  2. the moving median rejects a single-sample spike exactly;
  3. the deadband judge is a Schmitt trigger: WITHIN (no post) at
     d = delta, SNAP (post, reality wins, debt booked) at d = delta + 1;
  4. the QUF state line carries the whole image as integer key=value
     pairs with the dial named in the cell;
  5. the generated C contains no floating-point types (the ST 5.3
     float-free-loop property is checked, not assumed).

FOUNDATION 4: verification is the judgment that two interpretations of
one cell agree -- here the Python model and the compiled C must agree on
every golden vector, exactly.

Usage:  python3 verify.py [CELL.yaml]     (default: oil-pressure-port)
Exit 0 = PASS, 1 = FAIL. Stdlib only.
"""

import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import emith  # noqa: E402

# Hand-computed golden anchors (mV -> whole psi), independent of both the
# generator and the model below. On-lattice rows: every 400 mV is exactly
# 15 psi ((mV-500)*3/80 lands on whole psi). Off-lattice rows exercise
# round-to-nearest; 475/4600 mV exercise the [0,150] clamp.
HAND_GOLDEN = [
    (500, 0), (900, 15), (1300, 30), (1700, 45), (2100, 60), (2500, 75),
    (2900, 90), (3300, 105), (3700, 120), (4100, 135), (4500, 150),
    (750, 9), (1000, 19), (2750, 84), (4499, 150), (475, 0), (4600, 150),
]

STUB = r"""/* host-side verification stub -- GENERATED by tools/tower/verify.py.
 * Overrides the two weak glue points of the generated cell, stages the
 * golden vectors, prints RESULT lines the Python gate cross-checks.
 */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h>

TOWER_DECLS

static int32_t  g_mV = 0;
static unsigned g_posts = 0;
static char     g_last_ep[128];
static char     g_last_line[256];

int32_t tower_adc_read_mV(void) { return g_mV; }

void tower_twin_post(const char *endpoint, const char *state_line)
{
    snprintf(g_last_ep, sizeof g_last_ep, "%s", endpoint);
    snprintf(g_last_line, sizeof g_last_line, "%s", state_line);
    g_posts++;
}

static void feed(int32_t mV, int n)
{
    int i;
    g_mV = mV;
    for (i = 0; i < n; i++) {
        tower_tick();
    }
}

static int g_fail = 0;

static void reset_cell(void)
{
    tower_reset();
    g_posts = 0;
}

static void expect(const char *what, long got, long want)
{
    if (got == want) {
        printf("OK   %s got=%ld\n", what, got);
    } else {
        g_fail++;
        printf("FAIL %s got=%ld want=%ld\n", what, got, want);
    }
}

struct row { int mV; int psi; };
static const struct row GOLD[] = {TOWER_GOLD_ROWS};

int main(void)
{
    size_t k;
    char line[256];
    size_t n;

    /* 1. golden rendering table, whole-unit exact */
    for (k = 0; k < sizeof GOLD / sizeof GOLD[0]; k++) {
        char what[48];
        reset_cell();
        feed(GOLD[k].mV, TOWER_WINDOW);
        snprintf(what, sizeof what, "golden mV=%d", GOLD[k].mV);
        expect(what, tower_psi_whole(), GOLD[k].psi);
    }

    /* 2. median rejects a single spike */
    reset_cell();
    feed(1000, TOWER_WINDOW);
    expect("median warm at 1000 mV", tower_psi_whole(), PSI_AT_1000);
    feed(4500, 1);
    expect("median rejects 4500 mV spike", tower_psi_whole(), PSI_AT_1000);
    feed(1000, 1);
    expect("median stable after spike", tower_psi_whole(), PSI_AT_1000);

    /* 3. deadband Schmitt: d == delta holds, d == delta+1 snaps */
    reset_cell();
    feed(2500, TOWER_WINDOW);
    expect("initial sync posts once", (long)g_posts, 1);
    expect("twin synced to 75 psi", tower_twin_psi(), 75);
    tower_twin_set_belief(74);
    feed(2500, 1);
    expect("WITHIN at d=1 (=delta): no post", (long)g_posts, 1);
    tower_twin_set_belief(77);
    feed(2500, 1);
    expect("SNAP at d=2 (>delta): posts", (long)g_posts, 2);
    expect("reality wins: twin back to 75", tower_twin_psi(), 75);
    expect("snap debt books +2 psi", tower_snap_debt(), 2);
    tower_twin_set_belief(76);
    feed(2500, 1);
    expect("WITHIN at d=1 again: no post", (long)g_posts, 2);

    printf("ENDPOINT %s\n", g_last_ep);

    /* 4. QUF state line */
    n = tower_quf_line(line, sizeof line);
    printf("QUFLINE %s\n", line);
    if (n == strlen(line)) {
        printf("OK   quf line nul-terminated at %lu\n", (unsigned long)n);
    } else {
        g_fail++;
        printf("FAIL quf line length %lu vs strlen %lu\n",
               (unsigned long)n, (unsigned long)strlen(line));
    }

    printf("SUMMARY failures=%d golden_rows=%lu\n", g_fail,
           (unsigned long)(sizeof GOLD / sizeof GOLD[0]));
    return g_fail ? 1 : 0;
}
"""


def model_psi(spec, mv):
    """Independent model of the rendering chain (no prefilter, constant
    input): clamp psi80 to the spec range, then round-to-nearest whole."""
    psi80 = (mv - spec["off_mv"]) * spec["num"]
    lo = spec["psi_min"] * spec["den"]
    hi = spec["psi_max"] * spec["den"]
    psi80 = max(lo, min(hi, psi80))
    return (psi80 + spec["den"] // 2) // spec["den"]


def find_compiler():
    for cc in ("gcc", "cc", "clang"):
        p = shutil.which(cc)
        if p:
            return p
    return None


def syntax_check(c_text):
    """Fallback when no host compiler exists: structural checks only."""
    issues = []
    if c_text.count("{") != c_text.count("}"):
        issues.append("unbalanced braces")
    if c_text.count("(") != c_text.count(")"):
        issues.append("unbalanced parens")
    for sym in ("tower_tick", "tower_quf_line", "tower_adc_read_mV",
                "tower_twin_post", "median_of", "judge_snap"):
        if sym not in c_text:
            issues.append("missing %s" % sym)
    if re.search(r"\b(float|double)\b", c_text):
        issues.append("floating-point type present")
    return issues


def main(argv=None):
    cell = argv[1] if len(argv) > 1 else os.path.join(
        HERE, "oil-pressure-port.cell.yaml")
    print("tower pilot verify -- SEMANTIC-TOWER end-to-end, one cell")
    print("  cell     : %s" % cell)

    spec, c_text = emith.compile_cell(cell)
    c_bytes = len(c_text.encode())
    c_lines = c_text.count("\n")
    print("  emitted  : tower_%s.c -- %d bytes, %d lines"
          % (spec["cname"], c_bytes, c_lines))

    failures = []

    # anchors: the hand table must agree with the independent model
    anchor_fail = 0
    for mv, psi in HAND_GOLDEN:
        if model_psi(spec, mv) != psi:
            anchor_fail += 1
            failures.append("hand golden %d mV: model says %d, hand says %d"
                            % (mv, model_psi(spec, mv), psi))
    print("  model    : %d/%d hand-golden anchors agree"
          % (len(HAND_GOLDEN) - anchor_fail, len(HAND_GOLDEN)))

    # property 5: float-free generated C
    if re.search(r"\b(float|double)\b", c_text):
        failures.append("generated C mentions a floating-point type")
    else:
        print("  floats   : none in generated C")

    cc = find_compiler()
    if cc is None:
        issues = syntax_check(c_text)
        if issues:
            failures.extend("syntax-check: " + i for i in issues)
            print("  compile  : SYNTAX-CHECK FAILED")
        else:
            print("  compile  : syntax-check only (no host compiler found)")
            print("             golden-table run SKIPPED -- not verified")
        for f in failures:
            print("  FAIL     : %s" % f)
        print("  RESULT   : %s" % ("FAIL" if failures else "PASS*"))
        return 1 if failures else 0

    # build + run the stub against the generated cell
    tmp = tempfile.mkdtemp(prefix="tower-verify-")
    gen_c = os.path.join(tmp, "tower_%s.c" % spec["cname"])
    stub_c = os.path.join(tmp, "stub_main.c")
    exe = os.path.join(tmp, "run")
    with open(gen_c, "w", encoding="utf-8") as f:
        f.write(c_text)

    decls = "\n".join(
        "%-8s %s;" % (t, n) for t, n in [
            ("int32_t", "tower_adc_read_mV(void)"),
            ("void", "tower_twin_post(const char *, const char *)"),
            ("void", "tower_tick(void)"),
            ("void", "tower_reset(void)"),
            ("size_t", "tower_quf_line(char *, size_t)"),
            ("int32_t", "tower_psi_whole(void)"),
            ("int32_t", "tower_twin_psi(void)"),
            ("int32_t", "tower_snap_debt(void)"),
            ("void", "tower_twin_set_belief(int32_t)"),
        ])
    rows = ",\n    ".join("{%d, %d}" % (mv, model_psi(spec, mv))
                          for mv, _ in HAND_GOLDEN)
    stub = (STUB
            .replace("TOWER_DECLS", decls)
            .replace("TOWER_GOLD_ROWS", rows)
            .replace("TOWER_WINDOW", str(spec["window"]))
            .replace("PSI_AT_1000", str(model_psi(spec, 1000))))
    with open(stub_c, "w", encoding="utf-8") as f:
        f.write(stub)

    flags = ["-std=c99", "-Wall", "-Wextra", "-Werror", "-O2"]
    comp = subprocess.run([cc] + flags + [gen_c, stub_c, "-o", exe],
                          capture_output=True, text=True)
    cv = subprocess.run([cc, "--version"], capture_output=True, text=True)
    cc_name = (cv.stdout.splitlines() or [cc])[0].strip()
    print("  compiler : %s (%s)" % (cc, " ".join(flags)))
    if comp.returncode != 0:
        print("  compile  : FAILED\n%s" % comp.stderr)
        return 1
    print("  compile  : clean (-Werror), two TUs, weak-glue override linked")

    run = subprocess.run([exe], capture_output=True, text=True)
    out = run.stdout.splitlines()

    # cross-check every golden row against the independent model
    gold_ok = gold_seen = 0
    for line in out:
        m = re.match(r"^FAIL\s+(.*)$", line)
        if m:
            failures.append(m.group(1))
        m = re.match(r"^OK\s+golden mV=(\d+) got=(\d+)$", line)
        if m:
            gold_seen += 1
            want = model_psi(spec, int(m.group(1)))
            if int(m.group(2)) == want:
                gold_ok += 1
            else:
                failures.append("golden %s mV: C printed %s, model says %d"
                                % (m.group(1), m.group(2), want))
    if gold_seen != len(HAND_GOLDEN):
        failures.append("golden rows run: %d of %d"
                        % (gold_seen, len(HAND_GOLDEN)))
    else:
        print("  golden   : %d/%d voltage->PSI rows exact (whole-unit)"
              % (gold_ok, len(HAND_GOLDEN)))

    ep = next((l[len("ENDPOINT "):] for l in out
               if l.startswith("ENDPOINT ")), None)
    if ep != spec["endpoint"]:
        failures.append("endpoint carried: %r != %r" % (ep,
                                                        spec["endpoint"]))
    else:
        print("  snap     : endpoint + Schmitt edges OK (WITHIN at d=D, "
              "SNAP at d=D+1, debt booked)")

    quf = next((l[len("QUFLINE "):] for l in out
                if l.startswith("QUFLINE ")), "")
    # final state: belief staged at 76, d=1 <= delta, so WITHIN -- belief
    # moves only on SNAP; the twin field stays 76 (the Schmitt hold).
    want_quf = {
        "cell": spec["name"], "tick": str(spec["window"] + 3),
        "raw_mV": "2500", "med_mV": "2500", "psi80": "6000", "psi": "75",
        "twin": "76", spec["dial"]: str(spec["deadband"]),
        "posts": "2", "snap_debt": "2",
    }
    got_quf = dict(kv.split("=", 1) for kv in quf.split()[1:])
    if got_quf != want_quf:
        failures.append("quf line: %r != %r" % (got_quf, want_quf))
    elif not re.fullmatch(r"QUF1 cell=[a-z0-9-]+( [A-Za-z_0-9]+=[-0-9]+)+",
                          quf):
        failures.append("quf line not all-integer key=value: %r" % quf)
    else:
        print("  quf line : exact image match, all values integer (%d kv)"
              % len(got_quf))

    summary = out[-1] if out else ""
    if not summary.startswith("SUMMARY failures=0"):
        failures.append("stub summary: %r" % (summary or "<none>"))
    shutil.rmtree(tmp, ignore_errors=True)

    for f in failures:
        print("  FAIL     : %s" % f)
    print("  RESULT   : %s" % ("FAIL" if failures else "PASS"))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
