// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VQ_FABRIC_TOP__SYMS_H_
#define VERILATED_VQ_FABRIC_TOP__SYMS_H_  // guard

#include "verilated.h"

// INCLUDE MODEL CLASS

#include "Vq_fabric_top.h"

// INCLUDE MODULE CLASSES
#include "Vq_fabric_top___024root.h"
#include "Vq_fabric_top_q_cell.h"

// DPI TYPES for DPI Export callbacks (Internal use)

// SYMS CLASS (contains all model state)
class alignas(VL_CACHE_LINE_BYTES)Vq_fabric_top__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    Vq_fabric_top* const __Vm_modelp;
    VlDeleter __Vm_deleter;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    Vq_fabric_top___024root        TOP;
    Vq_fabric_top_q_cell           TOP__q_fabric_top__DOT__nodes__BRA__0__KET____DOT__conn0__DOT__u_cell;
    Vq_fabric_top_q_cell           TOP__q_fabric_top__DOT__nodes__BRA__10__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell           TOP__q_fabric_top__DOT__nodes__BRA__11__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell           TOP__q_fabric_top__DOT__nodes__BRA__12__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell           TOP__q_fabric_top__DOT__nodes__BRA__13__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell           TOP__q_fabric_top__DOT__nodes__BRA__14__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell           TOP__q_fabric_top__DOT__nodes__BRA__1__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell           TOP__q_fabric_top__DOT__nodes__BRA__2__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell           TOP__q_fabric_top__DOT__nodes__BRA__3__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell           TOP__q_fabric_top__DOT__nodes__BRA__4__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell           TOP__q_fabric_top__DOT__nodes__BRA__5__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell           TOP__q_fabric_top__DOT__nodes__BRA__6__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell           TOP__q_fabric_top__DOT__nodes__BRA__7__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell           TOP__q_fabric_top__DOT__nodes__BRA__8__KET____DOT__connc__DOT__u_cell;
    Vq_fabric_top_q_cell           TOP__q_fabric_top__DOT__nodes__BRA__9__KET____DOT__connc__DOT__u_cell;

    // SCOPE NAMES
    VerilatedScope __Vscope_TOP;
    VerilatedScope __Vscope_q_fabric_top;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____conn0__u_cell;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____conn0__u_cell__edges__BRA__0__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____conn0__u_cell__edges__BRA__0__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____conn0__u_cell__edges__BRA__1__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____conn0__u_cell__edges__BRA__1__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____conn0__u_cell__edges__BRA__2__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____conn0__u_cell__edges__BRA__2__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____conn0__u_cell__edges__BRA__3__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____conn0__u_cell__edges__BRA__3__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____conn0__u_cell__u_core;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____conn0__u_cell__u_core__u_eg;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____conn0__u_cell__u_core__u_rq;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____conn0__u_cell__u_df;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____conn0__u_cell__u_egbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____conn0__u_cell__u_inbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____conn0__u_cell__u_rp;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__0__KET____u_pipe;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____connc__u_cell;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____connc__u_cell__edges__BRA__0__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____connc__u_cell__edges__BRA__0__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____connc__u_cell__edges__BRA__1__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____connc__u_cell__edges__BRA__1__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____connc__u_cell__edges__BRA__2__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____connc__u_cell__edges__BRA__2__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____connc__u_cell__edges__BRA__3__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____connc__u_cell__edges__BRA__3__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____connc__u_cell__u_core;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____connc__u_cell__u_core__u_eg;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____connc__u_cell__u_core__u_rq;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____connc__u_cell__u_df;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____connc__u_cell__u_egbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____connc__u_cell__u_inbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____connc__u_cell__u_rp;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__10__KET____u_pipe;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____connc__u_cell;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____connc__u_cell__edges__BRA__0__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____connc__u_cell__edges__BRA__0__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____connc__u_cell__edges__BRA__1__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____connc__u_cell__edges__BRA__1__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____connc__u_cell__edges__BRA__2__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____connc__u_cell__edges__BRA__2__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____connc__u_cell__edges__BRA__3__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____connc__u_cell__edges__BRA__3__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____connc__u_cell__u_core;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____connc__u_cell__u_core__u_eg;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____connc__u_cell__u_core__u_rq;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____connc__u_cell__u_df;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____connc__u_cell__u_egbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____connc__u_cell__u_inbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____connc__u_cell__u_rp;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__11__KET____u_pipe;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____connc__u_cell;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____connc__u_cell__edges__BRA__0__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____connc__u_cell__edges__BRA__0__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____connc__u_cell__edges__BRA__1__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____connc__u_cell__edges__BRA__1__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____connc__u_cell__edges__BRA__2__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____connc__u_cell__edges__BRA__2__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____connc__u_cell__edges__BRA__3__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____connc__u_cell__edges__BRA__3__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____connc__u_cell__u_core;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____connc__u_cell__u_core__u_eg;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____connc__u_cell__u_core__u_rq;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____connc__u_cell__u_df;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____connc__u_cell__u_egbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____connc__u_cell__u_inbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____connc__u_cell__u_rp;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__12__KET____u_pipe;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____connc__u_cell;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____connc__u_cell__edges__BRA__0__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____connc__u_cell__edges__BRA__0__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____connc__u_cell__edges__BRA__1__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____connc__u_cell__edges__BRA__1__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____connc__u_cell__edges__BRA__2__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____connc__u_cell__edges__BRA__2__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____connc__u_cell__edges__BRA__3__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____connc__u_cell__edges__BRA__3__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____connc__u_cell__u_core;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____connc__u_cell__u_core__u_eg;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____connc__u_cell__u_core__u_rq;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____connc__u_cell__u_df;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____connc__u_cell__u_egbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____connc__u_cell__u_inbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____connc__u_cell__u_rp;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__13__KET____u_pipe;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____connc__u_cell;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____connc__u_cell__edges__BRA__0__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____connc__u_cell__edges__BRA__0__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____connc__u_cell__edges__BRA__1__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____connc__u_cell__edges__BRA__1__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____connc__u_cell__edges__BRA__2__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____connc__u_cell__edges__BRA__2__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____connc__u_cell__edges__BRA__3__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____connc__u_cell__edges__BRA__3__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____connc__u_cell__u_core;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____connc__u_cell__u_core__u_eg;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____connc__u_cell__u_core__u_rq;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____connc__u_cell__u_df;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____connc__u_cell__u_egbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____connc__u_cell__u_inbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____connc__u_cell__u_rp;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__14__KET____u_pipe;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__15__KET____connio__u_io;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__15__KET____connio__u_io__u_rp;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__15__KET____u_pipe;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____connc__u_cell;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____connc__u_cell__edges__BRA__0__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____connc__u_cell__edges__BRA__0__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____connc__u_cell__edges__BRA__1__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____connc__u_cell__edges__BRA__1__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____connc__u_cell__edges__BRA__2__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____connc__u_cell__edges__BRA__2__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____connc__u_cell__edges__BRA__3__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____connc__u_cell__edges__BRA__3__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____connc__u_cell__u_core;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____connc__u_cell__u_core__u_eg;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____connc__u_cell__u_core__u_rq;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____connc__u_cell__u_df;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____connc__u_cell__u_egbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____connc__u_cell__u_inbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____connc__u_cell__u_rp;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__1__KET____u_pipe;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____connc__u_cell;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____connc__u_cell__edges__BRA__0__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____connc__u_cell__edges__BRA__0__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____connc__u_cell__edges__BRA__1__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____connc__u_cell__edges__BRA__1__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____connc__u_cell__edges__BRA__2__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____connc__u_cell__edges__BRA__2__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____connc__u_cell__edges__BRA__3__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____connc__u_cell__edges__BRA__3__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____connc__u_cell__u_core;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____connc__u_cell__u_core__u_eg;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____connc__u_cell__u_core__u_rq;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____connc__u_cell__u_df;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____connc__u_cell__u_egbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____connc__u_cell__u_inbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____connc__u_cell__u_rp;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__2__KET____u_pipe;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____connc__u_cell;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____connc__u_cell__edges__BRA__0__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____connc__u_cell__edges__BRA__0__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____connc__u_cell__edges__BRA__1__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____connc__u_cell__edges__BRA__1__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____connc__u_cell__edges__BRA__2__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____connc__u_cell__edges__BRA__2__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____connc__u_cell__edges__BRA__3__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____connc__u_cell__edges__BRA__3__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____connc__u_cell__u_core;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____connc__u_cell__u_core__u_eg;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____connc__u_cell__u_core__u_rq;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____connc__u_cell__u_df;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____connc__u_cell__u_egbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____connc__u_cell__u_inbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____connc__u_cell__u_rp;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__3__KET____u_pipe;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____connc__u_cell;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____connc__u_cell__edges__BRA__0__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____connc__u_cell__edges__BRA__0__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____connc__u_cell__edges__BRA__1__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____connc__u_cell__edges__BRA__1__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____connc__u_cell__edges__BRA__2__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____connc__u_cell__edges__BRA__2__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____connc__u_cell__edges__BRA__3__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____connc__u_cell__edges__BRA__3__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____connc__u_cell__u_core;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____connc__u_cell__u_core__u_eg;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____connc__u_cell__u_core__u_rq;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____connc__u_cell__u_df;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____connc__u_cell__u_egbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____connc__u_cell__u_inbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____connc__u_cell__u_rp;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__4__KET____u_pipe;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____connc__u_cell;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____connc__u_cell__edges__BRA__0__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____connc__u_cell__edges__BRA__0__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____connc__u_cell__edges__BRA__1__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____connc__u_cell__edges__BRA__1__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____connc__u_cell__edges__BRA__2__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____connc__u_cell__edges__BRA__2__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____connc__u_cell__edges__BRA__3__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____connc__u_cell__edges__BRA__3__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____connc__u_cell__u_core;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____connc__u_cell__u_core__u_eg;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____connc__u_cell__u_core__u_rq;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____connc__u_cell__u_df;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____connc__u_cell__u_egbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____connc__u_cell__u_inbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____connc__u_cell__u_rp;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__5__KET____u_pipe;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____connc__u_cell;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____connc__u_cell__edges__BRA__0__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____connc__u_cell__edges__BRA__0__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____connc__u_cell__edges__BRA__1__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____connc__u_cell__edges__BRA__1__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____connc__u_cell__edges__BRA__2__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____connc__u_cell__edges__BRA__2__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____connc__u_cell__edges__BRA__3__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____connc__u_cell__edges__BRA__3__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____connc__u_cell__u_core;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____connc__u_cell__u_core__u_eg;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____connc__u_cell__u_core__u_rq;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____connc__u_cell__u_df;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____connc__u_cell__u_egbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____connc__u_cell__u_inbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____connc__u_cell__u_rp;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__6__KET____u_pipe;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____connc__u_cell;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____connc__u_cell__edges__BRA__0__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____connc__u_cell__edges__BRA__0__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____connc__u_cell__edges__BRA__1__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____connc__u_cell__edges__BRA__1__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____connc__u_cell__edges__BRA__2__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____connc__u_cell__edges__BRA__2__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____connc__u_cell__edges__BRA__3__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____connc__u_cell__edges__BRA__3__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____connc__u_cell__u_core;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____connc__u_cell__u_core__u_eg;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____connc__u_cell__u_core__u_rq;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____connc__u_cell__u_df;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____connc__u_cell__u_egbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____connc__u_cell__u_inbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____connc__u_cell__u_rp;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__7__KET____u_pipe;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____connc__u_cell;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____connc__u_cell__edges__BRA__0__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____connc__u_cell__edges__BRA__0__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____connc__u_cell__edges__BRA__1__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____connc__u_cell__edges__BRA__1__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____connc__u_cell__edges__BRA__2__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____connc__u_cell__edges__BRA__2__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____connc__u_cell__edges__BRA__3__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____connc__u_cell__edges__BRA__3__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____connc__u_cell__u_core;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____connc__u_cell__u_core__u_eg;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____connc__u_cell__u_core__u_rq;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____connc__u_cell__u_df;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____connc__u_cell__u_egbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____connc__u_cell__u_inbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____connc__u_cell__u_rp;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__8__KET____u_pipe;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____connc__u_cell;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____connc__u_cell__edges__BRA__0__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____connc__u_cell__edges__BRA__0__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____connc__u_cell__edges__BRA__1__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____connc__u_cell__edges__BRA__1__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____connc__u_cell__edges__BRA__2__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____connc__u_cell__edges__BRA__2__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____connc__u_cell__edges__BRA__3__KET____u_hebb;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____connc__u_cell__edges__BRA__3__KET____u_hebb__g_lad_sat;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____connc__u_cell__u_core;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____connc__u_cell__u_core__u_eg;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____connc__u_cell__u_core__u_rq;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____connc__u_cell__u_df;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____connc__u_cell__u_egbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____connc__u_cell__u_inbuf;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____connc__u_cell__u_rp;
    VerilatedScope __Vscope_q_fabric_top__nodes__BRA__9__KET____u_pipe;
    VerilatedScope __Vscope_q_fabric_top__u_ts;

    // CONSTRUCTORS
    Vq_fabric_top__Syms(VerilatedContext* contextp, const char* namep, Vq_fabric_top* modelp);
    ~Vq_fabric_top__Syms();

    // METHODS
    const char* name() { return TOP.name(); }
};

#endif  // guard
