#!/usr/bin/env python3
"""G1 runway: group the 910 certificate clauses into symmetry families.

A family = set of clauses identical up to one ring/bit offset: replace
every literal's (bus, bit) with (bus, bit - anchor) where anchor is the
clause's minimum bus bit, then group by the resulting template.

Usage: group_clauses.py bare_inv.pla guarded_baked.aig guarded_aig.aim \
                        guarded_aig.il [out.md]
"""
import re, sys, json
from collections import defaultdict


def parse_aig_symbols(path):
    data = open(path, "rb").read()
    eol = data.index(b"\n")
    M, I, L, O, A = (int(x) for x in data[:eol].decode().split()[1:6])
    pos = eol + 1
    for _ in range(L):
        pos = data.index(b"\n", pos) + 1
    for _ in range(O):
        pos = data.index(b"\n", pos) + 1

    def rv(pos):
        s = v = 0
        while True:
            b = data[pos]; pos += 1
            v |= (b & 0x7F) << s; s += 7
            if not (b & 0x80):
                return v, pos
    for _ in range(A):
        _, pos = rv(pos); _, pos = rv(pos)
    sym = {}
    for line in data[pos:].split(b"\n"):
        t = line.decode().split()
        if t and t[0].startswith("l") and t[0][1:].isdigit() and len(t) > 1:
            sym.setdefault(int(t[0][1:]), t[1])
    return sym


def main(pla, aig, aim, il, out=None):
    sym = parse_aig_symbols(aig)
    varalias = {}
    for line in open(aim):
        t = line.split()
        if len(t) >= 4 and t[0] in ("latch", "init", "invlatch"):
            varalias.setdefault(int(t[1]), t[3])
    wires = {}
    for line in open(il):
        m = re.match(r"^  wire(?: width (\d+))?(?: signed| unsigned)? ([\\$].+)$",
                     line.rstrip("\n"))
        if m:
            wires[m.group(2)[1:]] = int(m.group(1) or 1)

    def resolve(k):
        for n in (sym.get(k), varalias.get(k)):
            if not n:
                continue
            base, bit = n, 0
            m = re.fullmatch(r"(.+)\[(\d+)\]", n)
            if m and m.group(1) in wires:
                base, bit = m.group(1), int(m.group(2))
            elif n not in wires:
                continue
            if 0 <= bit < wires[base]:
                return (base, bit)
        return None

    clauses = []
    ilb = []
    for line in open(pla):
        line = line.rstrip("\n")
        if line.startswith(".ilb"):
            ilb = [int(x[2:]) for x in line.split()[1:]]
        elif line.startswith(".") or line.startswith("#") or not line:
            continue
        else:
            cubes, o = line.split()
            if o == "1":
                clauses.append([(ilb[j], -1 if c == "1" else +1)
                                for j, c in enumerate(cubes) if c in "01"])

    fams = defaultdict(list)
    scalars = 0
    for cl in clauses:
        lits = []
        bits = []
        for k, pol in cl:
            r = resolve(k)
            if r is None:
                lits = None
                break
            base, bit = r
            if wires[base] == 1:
                lits.append((base, 0, pol))
            else:
                lits.append((base, bit, pol))
                bits.append(bit)
        if lits is None:
            scalars += 1
            continue
        # anchor on the ring position, not the fixed index-0 partner
        pos = [b for b in bits if b > 0]
        anchor = min(pos) if pos else (min(bits) if bits else 0)
        key = tuple(sorted(((b, i - anchor if i else "s", p) for b, i, p in lits),
                           key=lambda t: (t[0], str(t[1]), t[2])))
        fams[key].append((anchor, cl))
    fams = {k: v for k, v in fams.items() if v}

    single = sum(1 for v in fams.values() if len(v) == 1)
    sizes = sorted((len(v) for v in fams.values()), reverse=True)
    lines = [
        "# G1 clause-family analysis (auto-generated by group_clauses.py)",
        "",
        f"clauses: {len(clauses)}  (unresolvable-anchored: {scalars})",
        f"families: {len(fams)}  single-member: {single}",
        f"largest: {sizes[:10]}  members/family (mean "
        f"{len(clauses)/max(len(fams),1):.2f})",
        "",
        "| # | members | offsets (anchor bits) | template |",
        "|---|---------|----------------------|----------|",
    ]
    order = sorted(fams.items(), key=lambda kv: -len(kv[1]))
    for n, (key, members) in enumerate(order[:40], 1):
        offs = sorted(a for a, _ in members)
        tmpl = " | ".join(
            f"{'~' if p < 0 else ''}{b}"
            + (f"[{i}]" if i != "s" else "") for b, i, p in key)
        lines.append(f"| {n} | {len(members)} | {offs} | `{tmpl}` |")
    report = "\n".join(lines) + "\n"
    if out:
        open(out, "w").write(report)
        json.dump({repr(k): [a for a, _ in v] for k, v in fams.items()},
                  open(out + ".json", "w"))
    print(report.splitlines()[2])
    print(report.splitlines()[3])
    return fams


if __name__ == "__main__":
    main(*sys.argv[1:5], *(sys.argv[5:6] or [None]))
